name: CICD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
    branches: [ master ]

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

concurrency:
  group: 'runTests-${{ github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    shell: powershell

jobs:
  Deploy:
    runs-on: [ windows-latest ]
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          Write-Host "Upload to storage (preview)"
          $storageContext = New-AzStorageContext -UseConnectedAccount -StorageAccountName 'bccontainerhelper'

          Write-Host "Storage Context: $($storageContext.StorageAccountName)"

          New-AzureStorageContainer -Name 'public' -Context $storageContext -Permission 'Container' -ErrorAction Ignore | Out-Null